"""The question → SQL → data → visualization → insight pipeline.

Each stage is a separate service; this class only sequences them, reports progress, and turns
failures into a well-formed AnalysisResult. SQL generated by the model is repaired up to
`max_repairs` times when validation or execution fails, with the exact error fed back.
"""

import logging
from collections.abc import Callable
from typing import Any, Literal

from app.core.config import Settings
from app.core.errors import (
    AppError,
    DataSourceUnavailableError,
    LLMNotConfiguredError,
    LLMOutputError,
    QueryExecutionError,
    QueryTimeoutError,
)
from app.core.logging import log_event
from app.datasources.base import Connector
from app.llm.base import LLMProvider
from app.schemas.analysis import (
    AnalysisResult,
    Clarification,
    ErrorInfo,
    QueryResultData,
    SQLAttempt,
    SQLInfo,
    ValidationInfo,
)
from app.schemas.llm_outputs import SQLPlan
from app.services import schema_service
from app.services.chart_recommender import recommend_chart
from app.services.insight_generator import InsightGenerator, compute_facts
from app.services.query_executor import QueryExecutor
from app.services.sql_validator import SQLValidator, ValidationResult
from app.services.text_to_sql import FailedAttempt, PriorTurn, TextToSQLService

logger = logging.getLogger(__name__)

StepId = Literal["understand", "schema", "generate", "validate", "execute", "visualize", "insight"]
StepStatus = Literal["running", "done", "error", "skipped"]
Emit = Callable[[dict[str, Any]], None]


def _noop(_: dict[str, Any]) -> None:
    return None


class AnalysisPipeline:
    def __init__(
        self,
        *,
        settings: Settings,
        source_id: str,
        connector: Connector,
        provider: LLMProvider | None,
        business_notes: str | None = None,
        currency: str = "INR",
        emit: Emit | None = None,
    ) -> None:
        self.settings = settings
        self.source_id = source_id
        self.connector = connector
        self.provider = provider
        self.business_notes = business_notes
        self.currency = currency
        self._emit = emit or _noop

    def step(self, step: StepId, status: StepStatus, detail: str | None = None) -> None:
        self._emit({"type": "step", "step": step, "status": status, "detail": detail})

    # -- natural-language question ----------------------------------------------------------

    def run(self, question: str, history: list[PriorTurn]) -> AnalysisResult:
        result = AnalysisResult(status="error", question=question, currency=self.currency)
        self._attempts: list[SQLAttempt] = []
        try:
            return self._run(question, history, result)
        except AppError as exc:
            log_event(logger, "pipeline_failed", logging.WARNING, code=exc.code, detail=exc.detail)
            result.status = "error"
            result.error = ErrorInfo(code=exc.code, message=exc.message)
            return result
        except Exception:
            logger.exception("pipeline_crashed")
            result.status = "error"
            result.error = ErrorInfo(
                code="internal_error", message="Something went wrong while analysing this question."
            )
            return result
        finally:
            if result.sql is not None:
                result.sql.attempts = list(self._attempts)

    def _run(self, question: str, history: list[PriorTurn], result: AnalysisResult) -> AnalysisResult:
        self.step("understand", "running")
        if self.provider is None:
            self.step("understand", "error", "AI provider not configured")
            raise LLMNotConfiguredError()
        context = f"Using {len(history)} earlier turn(s) as context" if history else None
        self.step("understand", "done", context)

        self.step("schema", "running")
        snapshot = schema_service.get_schema(self.source_id, self.connector)
        relevance_text = " ".join([question, *(t.question for t in history[-2:])])
        tables = schema_service.select_tables(snapshot, relevance_text, self.settings.schema_table_budget)
        t2s = TextToSQLService(self.provider)
        system_prompt = t2s.build_system_prompt(
            dialect=self.connector.dialect,
            dialect_label=self.connector.dialect_label,
            schema_text=schema_service.render_schema(tables),
            latest_date=schema_service.latest_data_date(tables),
            business_notes=self.business_notes,
        )
        self.step("schema", "done", f"{len(tables)} of {len(snapshot.tables)} tables in context")

        validator = SQLValidator(snapshot, max_rows=self.settings.max_result_rows)
        executor = QueryExecutor(
            self.connector, timeout_s=self.settings.query_timeout_seconds, max_rows=self.settings.max_result_rows
        )
        failures: list[FailedAttempt] = []
        attempts = self._attempts

        while True:
            repairing = bool(failures)
            self.step(
                "generate", "running", f"Correcting the query (attempt {len(failures) + 1})" if repairing else None
            )
            plan = t2s.generate(system_prompt=system_prompt, question=question, history=history, failures=failures)
            result.interpretation = plan.interpretation
            result.title = plan.title
            result.reasoning_summary = plan.reasoning_summary

            if plan.status == "clarify":
                self.step("generate", "done", "Needs clarification")
                result.status = "clarification"
                result.clarification = Clarification(
                    question=plan.clarification_question or plan.interpretation,
                    options=plan.clarification_options[:4],
                )
                return result
            if plan.status == "unanswerable":
                self.step("generate", "done", "Not answerable from this data")
                result.status = "unanswerable"
                return result
            if not plan.sql:
                raise LLMOutputError("The AI model did not return a SQL query.")
            self.step("generate", "done")

            self.step("validate", "running")
            validation = validator.validate(plan.sql)
            result.sql = self._sql_info(plan, validation)
            if not validation.ok:
                attempts.append(SQLAttempt(sql=plan.sql, stage="validation", error=validation.error_message))
                self.step("validate", "error", validation.error_message)
                if len(failures) < self.settings.max_sql_repair_attempts:
                    failures.append(FailedAttempt(plan, "validation", validation.error_message))
                    continue
                result.status = "error"
                result.error = ErrorInfo(
                    code="sql_invalid", message=f"I couldn't produce a valid query. {validation.error_message}"
                )
                return result
            self.step(
                "validate",
                "done",
                "; ".join(validation.warnings) or "Read-only SELECT, all tables and columns verified",
            )

            self.step("execute", "running")
            try:
                data = executor.execute(validation)
            except QueryTimeoutError as exc:
                attempts.append(
                    SQLAttempt(sql=validation.validated_sql or plan.sql, stage="execution", error=exc.message)
                )
                self.step("execute", "error", exc.message)
                result.status = "error"
                result.error = ErrorInfo(code=exc.code, message=exc.message)
                return result
            except DataSourceUnavailableError:
                self.step("execute", "error", "Database unavailable")
                raise
            except QueryExecutionError as exc:
                attempts.append(
                    SQLAttempt(sql=validation.validated_sql or plan.sql, stage="execution", error=exc.message)
                )
                self.step("execute", "error", exc.message)
                if len(failures) < self.settings.max_sql_repair_attempts:
                    failures.append(FailedAttempt(plan, "execution", exc.message))
                    continue
                result.status = "error"
                result.error = ErrorInfo(
                    code=exc.code, message=f"I couldn't execute the generated query. {exc.message}"
                )
                return result
            attempts.append(SQLAttempt(sql=validation.validated_sql or plan.sql, stage="success"))
            self.step("execute", "done", f"{data.row_count:,} rows in {data.execution_ms} ms")
            break

        return self.analyze(result, data, hint=plan.chart_hint, measures=plan.measures)

    # -- shared by chat and the SQL workbench ------------------------------------------------

    def analyze(
        self,
        result: AnalysisResult,
        data: QueryResultData,
        *,
        hint: str = "auto",
        measures: list[str] | None = None,
        use_llm: bool = True,
    ) -> AnalysisResult:
        result.result = data
        if data.row_count == 0:
            self.step("visualize", "skipped", "No rows returned")
            self.step("insight", "skipped")
            result.status = "empty"
            return result

        self.step("visualize", "running")
        chart = recommend_chart(data, title=result.title or "", hint=hint, measures=measures)
        facts = compute_facts(data, chart, self.currency)
        result.chart = chart
        result.kpis = facts.kpis[:4] if data.row_count > 1 or chart.type == "kpi" else []
        self.step("visualize", "done", chart.type.replace("_", " "))

        self.step("insight", "running")
        generator = InsightGenerator(self.provider if use_llm else None)
        result.insight = generator.generate(
            question=result.question,
            interpretation=result.interpretation,
            result=data,
            facts=facts,
            currency=self.currency,
        )
        self.step("insight", "done")
        result.status = "success"
        return result

    def _sql_info(self, plan: SQLPlan, validation: ValidationResult) -> SQLInfo:
        return SQLInfo(
            dialect=self.connector.dialect_label,
            generated_sql=plan.sql or "",
            validated_sql=validation.validated_sql,
            validation=ValidationInfo(
                ok=validation.ok,
                errors=validation.errors,
                warnings=validation.warnings,
                limit_applied=validation.limit_applied,
                tables=validation.tables,
            ),
        )
